### ISSUE TITLE
[BUG] Fail to write to the logfile

### ISSUE THREAD

**Issue by truefriend-cz** [DrEmpiricism/Optimize-Offline#114] opened 2019-08-22 20:18 UTC
**Desktop (please complete the following information):**
 - OS being optimized: Windows 10 Pro
 - OS build: 1903 ENG, Win10_1903_V1_English_x64.iso
- Script version: 3.2.6.8

**Additional context**
Command line

**Log files**
Post-Optimization Image Health State: [Healthy]
Saving and Dismounting Microsoft Windows Recovery Environment (x64)
Rebuilding and Exporting Microsoft Windows Recovery Environment (x64)
Failed to Save and Dismount Microsoft Windows Recovery Environment (x64)
Fail to write to the logfile:The process cannot access the file 'C:\Script\OptimizeOfflineTemp_1232641977\WorkOffline\DISM.log' because it is being used by another process. (WimgapiCmdlet,Microsoft.Dism.Commands.ExportWindowsImageCommand: C:\Script\Optimize-Offline.ps1:1896 char:16)
Saving and Dismounting Windows 10 Pro

**Comment by DrEmpiricism** [comment] 2019-08-23 02:26
This is not a bug. Something outside of the script is interacting with the DISM log. In this particular instance, it occurred when the boot images were being rebuilt and exported. Another user had a similar issue occur when he had File Explorer (Windows Explorer) open with the Preview and Navigation Panes enabled which were unknowingly accessing the offline mount directories.

I'd start with closing running File Explorer processes and go from there.

**Closed** 2019-11-21 16:16 UTC
